package catan.API.response;

public enum Code {
    RolledSeven,
    RolledNotSeven,

    PlayerNoLumber,
    PlayerNoWool,
    PlayerNoGrain,
    PlayerNoBrick,
    PlayerNoOre,

    PlayerNotEnoughLumber,
    PlayerNotEnoughWool,
    PlayerNotEnoughGrain,
    PlayerNotEnoughBrick,
    PlayerNotEnoughOre,

    BankNoLumber,
    BankNoWool,
    BankNoGrain,
    BankNoBrick,
    BankNoOre,

    BankNotEnoughLumber,
    BankNotEnoughWool,
    BankNotEnoughGrain,
    BankNotEnoughBrick,
    BankNotEnoughOre,

    BankNoKnight,
    BankNoMonopoly,
    BankNoRoadBuilding,
    BankNoYearOfPlenty,

    NotConnectsToRoad,

    PlayerHasDev,
    PlayerNoDev,
    MonopolySuccess,
    KnightSuccess,
    RoadBuildingSuccess,
    YearOfPlentySuccess,
    ResourceNotSet,
    FirstResourceNotSet,
    SecondResourceNotSet,
    PlayerNoResource,
    NoRoad,
    NoSettlement,
    NoCity,
    BankNoRoad,
    BankNoSettlement,
    BankNoCity,
    BankNoDev,
    BankNoResource,
    IntersectionAlreadyOccupied,
    NotTwoRoadsDistance,
    SameTile,
    NoSuchIntersection,
    RoadAlreadyExistent,
    RoadInvalidPosition,
    RoadStartNotOwned,
    InvalidCityPosition,
    NotEnoughResources,
    InvalidSettlementPosition,
    TradeIsDone,
    InvalidTradeRequest,

    InvalidRequest
}
